services:
  db:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: fEeqsTech
      TZ: Asia/Tokyo
    volumes:
      - mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./mysql_log:/var/log/mysql
volumes:
  mysql:
    name: mysql-db-volume
    driver: local
